// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgLzvYXpquI49-zh0jdQatfA0SGm1dGeI',
    appId: '1:260188162127:web:74f2bb613d46fdb59e823a',
    messagingSenderId: '260188162127',
    projectId: 'egitim2-e4553',
    authDomain: 'egitim2-e4553.firebaseapp.com',
    storageBucket: 'egitim2-e4553.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-_uOgekh9CpUNNBPZOR2D5qwwBXNjEbI',
    appId: '1:260188162127:android:0c9aad736bc0d6729e823a',
    messagingSenderId: '260188162127',
    projectId: 'egitim2-e4553',
    storageBucket: 'egitim2-e4553.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzWNJT46eGuwxVogB84YNtu0__MdTi94o',
    appId: '1:260188162127:ios:99d0d72d2b5fd2e99e823a',
    messagingSenderId: '260188162127',
    projectId: 'egitim2-e4553',
    storageBucket: 'egitim2-e4553.firebasestorage.app',
    iosBundleId: 'com.example.egitim2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzWNJT46eGuwxVogB84YNtu0__MdTi94o',
    appId: '1:260188162127:ios:99d0d72d2b5fd2e99e823a',
    messagingSenderId: '260188162127',
    projectId: 'egitim2-e4553',
    storageBucket: 'egitim2-e4553.firebasestorage.app',
    iosBundleId: 'com.example.egitim2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgLzvYXpquI49-zh0jdQatfA0SGm1dGeI',
    appId: '1:260188162127:web:00b25b4894e27d249e823a',
    messagingSenderId: '260188162127',
    projectId: 'egitim2-e4553',
    authDomain: 'egitim2-e4553.firebaseapp.com',
    storageBucket: 'egitim2-e4553.firebasestorage.app',
  );

}